const BASE_SERVER = 'https://localhost:8000';
export const GROUP_ENDPOINT = (groupname) => `${BASE_SERVER}/group/${groupname}`;
export const SIGNIN_ENDPOINT = `${BASE_SERVER}/enter/signin`;
export const SIGNUP_ENDPOINT = `${BASE_SERVER}/enter/signup`;
export const NEWGROUP_ENDPOINT = `${BASE_SERVER}/enter/newgroup`;
export const RESTORE_SESSION_ENDPOINT = (groupname) => `${GROUP_ENDPOINT(groupname)}/action/restoresession`;
export const PIC_ENDOINT = (picurl) => `${BASE_SERVER}/pics/${picurl}`;
export const INVENTORY_ENDPOINT = (groupname) => `${GROUP_ENDPOINT(groupname)}/inventory`;
export const INVENTORY_SEARCH = (groupname) => `${INVENTORY_ENDPOINT(groupname)}/search`;
export const ADD_ITEM = (groupname, itemid) => `${INVENTORY_ENDPOINT(groupname)}/${itemid}/add`;
export const UPLOAD_PIC = (groupname) => `${GROUP_ENDPOINT(groupname)}/upload/pic`;
export const CREATE_ITEM = (groupname) => `${INVENTORY_ENDPOINT(groupname)}/create`;